#!/usr/bin/env zsh
export XDG_CONFIG_HOME="$HOME/.config"

if [ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
    source "$XDG_CONFIG_HOME/user-dirs.dirs"
fi

if [ -f "$XDG_CONFIG_HOME/local-dirs.dirs" ]; then
    source "$XDG_CONFIG_HOME/local-dirs.dirs"
fi

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zcompdump-$HOST"
export HISTFILE="$XDG_CACHE_HOME/zsh-history"

if command -v ksshaskpass > /dev/null 2>&1; then
    export SSH_ASKPASS=$(command -v ksshaskpass)
fi

LINK_DIR=~/.libs/PATH_INCLUDE
for link in $LINK_DIR/*; do
  if [ -L "$link" ]; then
    target="$LINK_DIR/$(readlink "$link")"
    if [ -d "$target" ]; then
      if [[ ":$PATH:" != *":$target:"* ]]; then
        export PATH="$target:$PATH"
      fi
    fi
  fi
done
export PATH="$HOME/.bin/:$PATH"
export GOPATH="$HOME/.libs/go"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export VIRSH_DEFAULT_CONNECT_URI=qemu:///system
